spring:
  application:
    name: aurora
  datasource:
    url: jdbc:postgresql://auroradb:5432/ddt2988qgiarh5
    username: postgresql
    # password: pce15b38ef9169b5f60bcae064b70202747cb647db8e757ff3e5ffe4f83c6a5d5
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        ddl-auto: update
    database: postgresql
    generate-ddl: true
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  web:
    resources:
      static-locations: aurora/src/main/resources/images/**
  messages:
    basename: lang/
upload:
  directory: aurora/src/main/resources/images/
  profilepictures:
    directory: aurora/src/main/resources/images/profilepictures
logging:
  level:
    org:
      springframework:
        web: DEBUG
        security: DEBUG
    root: info
server:
  port: ${PORT:8080}
