spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/auroradb
    username: marko
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        ddl-auto: auto
    database: postgresql
#    database-platform: org.hibernate.dialect.PostgreSQLDialect