spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/auroradb
    username: marko
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        ddl-auto: update
    database: postgresql
