spring:
  application:
    name: aurora
  datasource:
    url: jdbc:postgresql://localhost:5432/auroradb
    username: marko
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        ddl-auto: update
    database: postgresql
    generate-ddl: true
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  web:
    resources:
      static-locations: aurora/src/main/resources/images/**
  messages:
    basename: lang/
upload:
  directory: aurora/src/main/resources/images/
  profilepictures:
    directory: aurora/src/main/resources/images/profilepictures
logging:
  level:
    org:
      springframework:
        web: DEBUG
        security: DEBUG
    root: info
